const $=id=>document.getElementById(id);
let current={url:'',title:'',videoId:''};let lastTranscript='';
const PROMPTS={summarize:'Summarise this video with the main ideas, important facts, examples, and conclusions.',lecture:'Convert this into detailed lecture notes. Cover the source from beginning to end, preserve every important point, and do not omit examinable details.',linebyline:'Turn this into granular study notes in source order. Keep every important point; do not invent information or skip sections.',mcq:'Create high-quality MCQs from the source, covering all important concepts. Give the answer and a brief explanation after each question.'};
async function activeTab(){const ts=await chrome.tabs.query({active:true,currentWindow:true});return ts[0]}
async function context(){const t=await activeTab();if(!t)return null;current={url:t.url||'',title:t.title||'',videoId:''};if(/^https:\/\/(www\.)?youtube\.com\//.test(t.url||'')||/^https:\/\/youtu\.be\//.test(t.url||'')){try{const r=await chrome.tabs.sendMessage(t.id,{type:'GET_CONTEXT'});if(r?.ok)current={...current,...r}}catch{}}return current}
async function openUrl(url,copy=''){if(copy){try{await navigator.clipboard.writeText(copy)}catch{}}await chrome.tabs.create({url})}
async function refresh(){const c=await context();$('ytTitle').textContent=c?.isYouTube?c.title||'Current YouTube video':'Open a YouTube video';$('ytUrl').textContent=c?.isYouTube?c.url:'Open YouTube in the active tab.'}
async function copyPrompt(prompt){const text=(current.url?current.url+'\n\n':'')+prompt;try{await navigator.clipboard.writeText(text);return true}catch{return false}}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===b.dataset.tab))});
$('refresh').onclick=refresh;
$('openNlm').onclick=async()=>{await refresh();if(!current.url||!current.url.includes('youtube')){$('ytTitle').textContent='Open a YouTube video first';return}await openUrl('https://notebooklm.google.com/',current.url+'\n\nIn NotebookLM: Add source → YouTube → paste the URL.');};
$('openStudio').onclick=async()=>{await refresh();if(!current.url||!current.url.includes('youtube')){$('ytTitle').textContent='Open a YouTube video first';return}await copyPrompt(PROMPTS.lecture);await chrome.tabs.create({url:'https://aistudio.google.com/'});$('ytTitle').textContent='AI Studio opened. Upload the video, then paste the copied prompt.'};
$('transcript').onclick=async()=>{const t=await activeTab();if(!t?.id||!current.url.includes('youtube')){$('transcriptOut').textContent='Open a YouTube video first.';return}$('transcriptOut').textContent='Reading YouTube transcript…';try{const r=await chrome.tabs.sendMessage(t.id,{type:'GET_TRANSCRIPT'});if(!r?.ok){$('transcriptOut').textContent=r?.error||'No readable transcript found.';return}lastTranscript=r.lines.join('\n');$('transcriptOut').textContent=lastTranscript.slice(0,8000)+(lastTranscript.length>8000?'\n…':'');$('copyTranscript').disabled=false}catch(e){$('transcriptOut').textContent='Transcript unavailable. Open Show transcript in YouTube and try again.'}};
$('copyTranscript').onclick=async()=>{await navigator.clipboard.writeText(lastTranscript);$('copyTranscript').textContent='Copied';setTimeout(()=>$('copyTranscript').textContent='Copy',900)};
document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=async()=>{await copyPrompt(PROMPTS[b.dataset.prompt]);b.textContent='Copied ✓';setTimeout(()=>b.textContent=PROMPTS[b.dataset.prompt],1200)});
$('collectLinks').onclick=async()=>{const t=await activeTab();if(!t?.id){return}try{const r=await chrome.tabs.sendMessage(t.id,{type:'COLLECT_LINKS'});if(!r?.links?.length){$('ytTitle').textContent='No loaded YouTube links found.';return}await navigator.clipboard.writeText(r.links.join('\n'));$('ytTitle').textContent='Copied '+r.links.length+' YouTube links.'}catch{ $('ytTitle').textContent='Open a YouTube playlist/channel/search page and retry.' }};
$('pdfFile').onchange=()=>{$('pdfStatus').textContent=$('pdfFile').files[0]?('Selected: '+$('pdfFile').files[0].name):'Waiting for PDF.'};
$('split').onclick=async()=>{const f=$('pdfFile').files[0];const parts=Math.max(1,Math.min(100,Number($('parts').value)||20));if(!f){$('pdfStatus').textContent='Choose a PDF first.';return}if(f.size>4*1024*1024){$('pdfStatus').textContent='This server route accepts PDFs up to about 4 MB. Use the FreeToolForge web PDF workspace for larger files.';return}const form=new FormData();form.append('file',f,f.name);form.append('parts',String(parts));$('pdfStatus').textContent='Splitting…';try{const r=await fetch('https://freetoolforge-ocr-ziyadshafeeks-projects.vercel.app/api/split-pdf',{method:'POST',body:form});if(!r.ok){$('pdfStatus').textContent='Split failed ('+r.status+').';return}const blob=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=f.name.replace(/\.pdf$/i,'')+'-sections.zip';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);$('pdfStatus').textContent='Done. ZIP downloaded with section PDFs + prompts.'}catch(e){$('pdfStatus').textContent='Split error: '+e.message}};
$('ocrFile').onchange=()=>{$('ocrStatus').textContent=$('ocrFile').files[0]?('Selected: '+$('ocrFile').files[0].name):'Waiting for image.'};
$('ocrRun').onclick=async()=>{const f=$('ocrFile').files[0];if(!f){$('ocrStatus').textContent='Choose an image first.';return}if(f.size>3.5*1024*1024){$('ocrStatus').textContent='Image too large for this background route.';return}const form=new FormData();form.append('file',f,f.name);form.append('language','eng');$('ocrStatus').textContent='Background OCR running…';try{const r=await fetch('https://freetoolforge-ocr-ziyadshafeeks-projects.vercel.app/api/ocr',{method:'POST',body:form});const j=await r.json();$('ocrStatus').textContent=j.ok?(j.text||'No text found.'):(j.message||j.error||'OCR failed');}catch(e){$('ocrStatus').textContent='OCR error: '+e.message}};
refresh();
