import json,re,pathlib
cats={
'PDF':['Merge PDFs','Split PDF','Compress PDF','Repair PDF','OCR PDF','Redact PDF','Sign PDF','Fill PDF','Annotate PDF','Rotate PDF','Reorder PDF Pages','Extract PDF Pages','Delete PDF Pages','Extract PDF Images','PDF Metadata Viewer','Remove PDF Metadata','Add PDF Watermark','Add PDF Page Numbers','Overlay PDFs','Compare PDFs','Crop PDF','Resize PDF Pages','PDF to Images','PDF to Text','PDF to Markdown','PDF to HTML','PDF to Word','PDF to Excel','PDF to PowerPoint','PDF to EPUB','PDF to RTF','Images to PDF','JPG to PDF','PNG to PDF','WEBP to PDF','HEIC to PDF','Word to PDF','Excel to PDF','PowerPoint to PDF','Text to PDF','Markdown to PDF','HTML to PDF','EPUB to PDF','PDF/A Helper','Booklet PDF Maker','Pages per Sheet','Two Pages per Sheet','PDF Page Counter','PDF Bookmark Helper','PDF Form Field Viewer','Invoice PDF Maker','PDF Batch Rename','PDF Page Extractor'],
'Images':['Image Compressor','Image Resizer','Image Cropper','Image Rotator','Image Flipper','JPG to PNG','PNG to JPG','WEBP to JPG','JPG to WEBP','PNG to WEBP','AVIF Converter','HEIC Converter','TIFF Converter','SVG Previewer','SVG to PNG','Favicon Generator','ICO Converter','Image Dimensions','Color Picker','Palette Generator','Dominant Color Finder','Contrast Checker','EXIF Viewer','Remove EXIF','Image Blur','Image Pixelate','Image Sharpen','Image Watermark','Image Background Remover','Image Border Maker','Image Padding Tool','Image Collage Maker','Contact Sheet Maker','Sprite Sheet Maker','Passport Photo Cropper','Signature Cropper','Scan Cleanup','Screenshot Cropper','Image to PDF','Image OCR','Image Difference','Image Average Color','Image File Size Calculator','DPI Calculator','Print Size Calculator','Social Image Resizer','Thumbnail Maker','Photo Strip Maker','Round Image Maker','Transparent PNG Maker'],
'Audio':['Audio Denoiser','Speech Cleanup','Audio Dereverb','Voice Isolation','Audio Trimmer','Audio Cutter','Audio Merger','Audio Splitter','Audio Normalizer','Audio Compressor','WAV to MP3','MP3 to WAV','M4A to MP3','OGG to MP3','FLAC Converter','Audio Duration','Silence Detector','Silence Remover','Mono to Stereo','Stereo to Mono','Sample Rate Converter','Volume Changer','Audio Metadata Viewer','Remove Audio Metadata','Waveform Viewer','Audio Fade In','Audio Fade Out','Podcast Loudness Checker','Podcast Intro Trimmer','Speech to Text','Transcript Cleaner'],
'Video':['Video Compressor','Video Trimmer','Video Cutter','Video Merger','Extract Audio','Extract Frames','Video to GIF','GIF to MP4','MP4 to WebM','WebM to MP4','Resize Video','Crop Video','Rotate Video','Mute Video','Video Thumbnail Extractor','Video Contact Sheet','Subtitle Extractor','Subtitle Formatter','Subtitle Timing Helper','Transcript to SRT','SRT to VTT','VTT to SRT','Frame Rate Calculator','Video Duration','Video Bitrate Calculator','Video Metadata Viewer'],
'OCR & AI':['OCR Image to Text','OCR PDF','Handwriting OCR','Receipt OCR','Invoice OCR','Table OCR','Form OCR','ID Document OCR','Document Classifier','Document JSON Extractor','Smart Note Maker','Lecture Note Maker','Meeting Note Maker','Transcript Summarizer','Study Guide Maker','Flashcard Maker','Quiz Maker','Action Item Extractor','Citation Extractor','Abstract Summarizer','Key Point Extractor','Email Summarizer','Text Rewriter','Text Cleaner','Entity Extractor'],
'Text':['Word Counter','Character Counter','Sentence Counter','Paragraph Counter','Reading Time Calculator','Case Converter','Title Case','Uppercase Converter','Lowercase Converter','Whitespace Cleaner','Trim Lines','Remove Duplicate Lines','Sort Lines','Reverse Lines','Number Lines','List to CSV','CSV to List','Text Diff','Find and Replace','Slug Generator','Markdown Cleaner','HTML Text Extractor','Text to QR','QR to Text','Morse Encoder','Morse Decoder','NATO Phonetic Converter','Leetspeak Converter','Unicode Inspector','Unicode Normalizer','Text Repeater','Random Line Picker','Random Word Picker','Lorem Ipsum Generator','Palindrome Checker','Anagram Checker','Text Statistics'],
'Developer':['JSON Formatter','JSON Minifier','JSON Validator','JSON to CSV','CSV to JSON','YAML Formatter','XML Formatter','XML Validator','Base64 Encoder','Base64 Decoder','URL Encoder','URL Decoder','JWT Decoder','UUID Generator','Nano ID Generator','SHA-256 Hash','SHA-512 Hash','MD5 Hash','HMAC Helper','Regex Tester','Regex Generator Helper','Cron Expression Helper','Unix Timestamp Converter','Epoch Converter','HTTP Header Viewer','User-Agent Parser','MIME Type Lookup','URL Parser','HTML Escape','HTML Unescape','SQL Formatter','Markdown Preview','JSON Path Helper','JSON Pointer Helper','Semver Calculator','Color Hex Converter','RGB HSL Converter','CSS Minifier','JS Minifier','HTML Minifier','IP Subnet Calculator','CIDR Calculator','Byte Converter','File Hash Checker','Random Hex Generator','Random String Generator','Package Name Checker'],
'Calculators':['Percentage Calculator','Discount Calculator','Tip Calculator','Markup Calculator','Margin Calculator','Profit Calculator','Break Even Calculator','GST Calculator','Sales Tax Calculator','VAT Calculator','EMI Calculator','Loan Amortization','Compound Interest','Simple Interest','Inflation Calculator','ROI Calculator','ROAS Calculator','Salary Calculator','Hourly Rate Calculator','Age Calculator','Date Difference','Business Days Calculator','Time Difference','Time Zone Converter','Unit Converter','Length Converter','Weight Converter','Temperature Converter','Area Converter','Volume Converter','Speed Converter','Data Size Converter','BMI Calculator','BSA Calculator','Anion Gap Calculator','Corrected Calcium Calculator','Creatinine Clearance','Body Fat Calculator','Calorie Estimate','IV Flow Rate Helper','Drug Dilution Helper','Concentration Calculator','Molarity Calculator'],
'Business':['Invoice Maker','Quotation Maker','Receipt Maker','Purchase Order Maker','Proforma Invoice','Credit Note Maker','Debit Note Maker','Delivery Challan','Packing Slip','Payslip Maker','Timesheet Maker','Attendance Sheet','Expense Report','Petty Cash Sheet','Inventory Sheet','SKU Generator','Barcode Generator','Label Maker','Business Card Maker','Letterhead Maker','Email Signature Maker','Proposal Maker','SOP Maker','Meeting Minutes Maker','Meeting Agenda Maker','Purchase Tracker','Pricing Calculator','Cashflow Calculator','Break Even Dashboard','UTM Builder','QR Business Card','Shipping Label Maker','Expense Splitter','Commission Calculator','Sales Target Calculator','Payroll Calculator','Invoice Number Generator'],
'Education':['CGPA Calculator','Grade Calculator','Marks Percentage','Study Planner','Study Timer','Pomodoro Timer','Flashcard Maker','Quiz Maker','MCQ Worksheet Maker','Citation Formatter','APA Citation Helper','MLA Citation Helper','Chicago Citation Helper','Vancouver Citation Helper','Reference List Cleaner','Reading Time Calculator','Note Outline Maker','Lecture Note Formatter','PDF Study Pack Maker','Question Paper Formatter','Answer Sheet Generator','Timetable Maker','Exam Countdown','Semester Planner','GPA Converter'],
'India':['GSTIN Format Checker','GST Calculator India','PAN Format Helper','IFSC Lookup Interface','Pincode Formatter','Post Office Formatter','Indian Number Formatter','Lakh Crore Converter','Indian Date Formatter','UPI QR Payload Builder','Aadhaar Masking Helper','Vehicle Number Formatter','Indian Salary Calculator','Indian Tax Calculator','TDS Calculator','Professional Tax Helper','E Invoice Field Helper','HRA Calculator','Gratuity Calculator','PF Calculator','ESI Calculator','Indian Time Zone Converter'],
'Privacy & Security':['PII Masker','Email Masker','Phone Number Masker','Text Anonymizer','EXIF Viewer','Metadata Inspector','Remove Metadata','Secure Password Generator','Passphrase Generator','Password Strength Checker','URL Privacy Cleaner','JWT Decoder','HTTP Security Header Viewer','CSP Helper','Robots.txt Viewer','Sitemap Viewer','TLS Certificate Inspector','Redirect Chain Viewer','DNS Record Viewer','IP/ASN Lookup Interface','Public URL Inspector','Image Perceptual Hash','File Hash Checker'],
'OSINT / Public Data':['URL Metadata Inspector','DNS Lookup','ASN Lookup','TLS Certificate Inspector','HTTP Headers Inspector','Redirect Chain Inspector','Robots.txt Inspector','Sitemap Inspector','Public Profile URL Checker','Username Permutation Generator','Public Social Link Extractor','Public Instagram URL Inspector','Public Page Metadata Inspector','Favicon Extractor','Image EXIF Inspector','Image Perceptual Hash','Domain WHOIS Interface','Email Domain Hygiene Checker','Phone Country Analyzer','IP Address Parser'],
'Files & Data':['CSV Cleaner','CSV Deduplicator','CSV Column Selector','CSV Splitter','CSV Merger','CSV Transposer','CSV to TSV','TSV to CSV','JSON Lines Cleaner','JSON Lines Merger','TXT to CSV','CSV to XLSX','XLSX to CSV','File Renamer Pattern Generator','Folder Tree Generator','File Extension Extractor','Duplicate Filename Finder','File Size Calculator','Checksum Manifest Generator','Data URI Encoder','Data URI Decoder','Line Ending Converter','UTF-8 Inspector','Binary Viewer Helper'],
'Productivity':['QR Code Generator','Barcode Generator','Random Picker','Checklist Maker','Decision Table Maker','Meeting Agenda','Meeting Minutes','Task Priority Matrix','Habit Tracker','Countdown Timer','Stopwatch','Pomodoro','Calendar Week Number','Date Planner','Business Days Counter','Timezone Meeting Planner','File Name Cleaner','Text Joiner','Table Maker','CSV Previewer'],
'Design & Web':['Color Palette Generator','Gradient Generator','Box Shadow Generator','Border Radius Generator','CSS Grid Generator','CSS Flexbox Generator','Responsive Breakpoint Helper','Meta Tag Generator','Open Graph Generator','Twitter Card Generator','Schema Markup Generator','Canonical Tag Generator','Robots Meta Generator','Sitemap XML Generator','Favicon Pack Generator','Web Manifest Generator','QR Landing Page Maker','OG Image Maker','Placeholder Image Generator','SVG Pattern Generator'],
'Finance':['Compound Interest','Loan Payment','Amortization','Investment Return','Net Worth Tracker','Budget Sheet','Savings Goal','Emergency Fund Calculator','Debt Snowball','Debt Avalanche','Inflation Adjuster','Currency Converter','Profit Margin','Markup','Break Even','Discount','Tax Calculator','Commission Calculator','Subscription Cost Calculator','CAC Calculator','LTV Calculator'],
'Media / Downloads':['YouTube Video Downloader','YouTube Audio Extractor','YouTube Thumbnail Downloader','YouTube Subtitle Helper','SlideShare Downloader','Public Video Frame Extractor','Webpage Asset Saver','Public Image Downloader'],
'Health & Medical':['BMI Calculator','BSA Calculator','Anion Gap Calculator','Corrected Calcium Calculator','Creatinine Clearance','eGFR Reference Helper','Ideal Body Weight','Adjusted Body Weight','Osmolality Calculator','Sodium Correction','QTc Calculator','MAP Calculator','Pulse Pressure','Mean Arterial Pressure','Drip Rate Calculator','IV Flow Rate','Concentration Calculator','Dilution Calculator','Unit Conversion','Medical Abbreviation Helper','Clinical Note Formatter'],
'Miscellaneous':['Dice Roller','Coin Flip','Random Number Generator','Random Name Picker','Team Generator','Decision Wheel','QR Code','Barcode','Color Blindness Simulator','Typing Speed Test','Keyboard Test','Mouse Test','Screen Resolution Checker','Browser Feature Checker','Network Speed Test Interface','Internet Time Checker','World Clock','Calendar Generator','Printable Ruler','A4 Paper Generator']
}
# Assign statuses: exact small browser utilities live; heavier/complex ones beta; broad catalog otherwise.
live_keywords={'Counter','Formatter','Minifier','Validator','Encoder','Decoder','Generator','Calculator','Converter','Checker','Cleaner','Picker','Sorter','Repeater','Slug','Timestamp','UUID','Hash','QR','Barcode','Text Diff','Case','Whitespace','Trim','Reverse','Number Lines','Morse','Palindrome','Anagram','RGB','Hex','URI','URL ','Base64','Random','Age','Date Difference','Time Difference','Unit','Percentage','Discount','Tip','Margin','Markup','Profit','Break Even','GST','VAT','ROI','ROAS','Reading Time','CGPA','Grade','Marks Percentage','Pincode','Lakh Crore','Indian Number','Aadhaar Masking','Vehicle Number','File Size','Byte','Data Size'}

def slug(s): return re.sub(r'-+','-',re.sub(r'[^a-z0-9]+','-',s.lower())).strip('-')
seen=set(); out=[]
for cat,names in cats.items():
    for title in names:
        sl=slug(title)
        if sl in seen: continue
        seen.add(sl)
        status='live' if any(k.lower() in title.lower() for k in live_keywords) else ('beta' if cat in {'PDF','Images','Audio','Video','OCR & AI','OSINT / Public Data','Media / Downloads'} else 'catalogued')
        processing='browser'
        if cat in {'OSINT / Public Data'} or title in {'DNS Lookup','ASN Lookup','IP/ASN Lookup Interface','Domain WHOIS Interface','Public Instagram URL Inspector','Public Profile URL Checker','Public Page Metadata Inspector','TLS Certificate Inspector','HTTP Headers Inspector','Redirect Chain Inspector','Robots.txt Inspector','Sitemap Inspector'}:
            processing='server'
        if cat in {'Audio','Video','OCR & AI','PDF'} and status!='live': processing='hybrid'
        out.append({'slug':sl,'title':title,'category':cat,'status':status,'processing':processing,'description':f'Free {cat.lower()} utility for {title.lower()}.','privacy':'local where practical','adSlots':['top','inline','bottom']})
pathlib.Path('data/tools.json').write_text(json.dumps(out,indent=2,ensure_ascii=False)+'\n')
print(len(out))
